API/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns

from API.views import *

router = routers.DefaultRouter()
router.include_format_suffixes = False
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^current_user/$', current_user),
    url(r'^posts/$', posts),
    url(r'^notifications/$', notifications),
    url(r'^public-relations/$', publicRelationsView.as_view()),
    url(r'^all-notifications/$', all_notifications),
    url(r'^leaderboard/$', leaderboard),
    url(r'^ca-profile/$', CAProfileUpdate),
    url(r'^ky-profile/$', KYProfileUpdate),
    url(r'^updatecauser/$', updateCAUser),
    url(r'^all-event/$', allEvent),
    url(r'^teamregister/$', registerTeam),
    url(r'^get-reg/$', getReg),
    url(r'^indregister/$', registerIndi),
    url(r'^deleteteam/$', deleteteam),
    url(r'^referedreg/$', getReferedReg),

    url(r'^sub-event/(?P<eventName>[\w|\W]+)$',subEvent),

    ##mobile app
    url(r'^mobile/login/$', mobileLogin),
    url(r'^mobile/register/$', mobileRegister),
    url(r'^mobile/notifications/$', mobileNotifications),

    url(r'^mobile/login/social/$', mobileSocialLogin),


]

urlpatterns = format_suffix_patterns(urlpatterns)

event/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.contrib import admin
from event.views import *

app_name='event'

urlpatterns = [
	
	url(r'^events/$', eventPage, name= 'events_index'),
	url(r'^events/(?P<eventCatName>[\w|\W]+)$', eventCatPage, name= 'events_category_reg'),
	url(r'^events/teamRegister/(?P<eventName>[\w|\W]+)$', eventRegistration, name= 'events_reg'),
	url(r'^events/individualRegister/$', individualReg, name= 'ind_reg'),
	url(r'^regCheck/$', regCheckAjax, name= 'events_reg'),


]

kashiyatra/urls.py
from django.conf.urls import url, include
from django.shortcuts import redirect
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.defaults import page_not_found
from django.contrib.auth.views import logout
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.generic import RedirectView

from .settings import STATICFILES_DIRS

def lafda(request, shit):
    return redirect('/')

urlpatterns = [
    url(r'^(?P<shit>[\w{}.-]{5})/', lafda),
    url(r'^api/', include('API.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^ky-the-admin/', admin.site.urls),
    # url(r'^account/social/signup/',TemplateView.as_view(template_name='ca-redirect.html')),
    ##url(r'^account/email',page_not_found, {'exception': Exception('Not Found')}),
    ##url(r'^account/signup/$',lambda x: redirect('/form')),
    ##url(r'^account/login/$', lambda x: redirect('/account/facebook/login/')),
    ##url(r'^account/password/',page_not_found, {'exception': Exception('Not Found')}),
    # url(r'^account/confirm-email',page_not_found, {'exception': Exception('Not Found')}),
    ##url(r'^account/', include('allauth.urls')),
    url(r'^', include('users.urls')),
    url(r'^', include('etc.urls')),
    url(r'^',include('event.urls')),
    url(r'^(?!/?static/)(?!/?media/)(?P<path>.*\..*)$',
        RedirectView.as_view(url='/static/%(path)s', permanent=False)),
]

users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from .views import *
from . import views

urlpatterns = [
    url(r'^$', IndexView),
    url(r'^ca/$', CAIndexView),
#     url(r'^form/$', FormView),
    url(r'^user-form/$', UserFormView),
    url(r'^ca-form/$', CaFormView),
    url(r'^email_reg/$', EmailRegistration),
    url(r'^dashboard', DashboardView, name="ca-dashboard"),
    url(r'^privacy_policy/$', PrivacyPolicyView,),
    url(r'^reset_/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset_, name='reset_'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    
    url(r'^logout/$', LogoutView),
    url(r'^eventRegister/$', eventRegister),
    url(r'^forgotPass/$', forgotPassword),

]

event/models.py
from django.db import models
from users.models import KYProfile

class ParentEvent(models.Model):
    parentEventId = models.AutoField(primary_key = True)
    categoryName = models.CharField(max_length = 50)

    def __str__(self):
        return "Category: %s" %self.categoryName


class Event(models.Model):
    eventId = models.AutoField(primary_key=True)
    eventName = models.CharField(max_length=50)
    eventDetails = models.TextField()
    maxMembers = models.PositiveSmallIntegerField(null=True,blank=True)
    minMembers = models.PositiveSmallIntegerField(null=True,blank=True)
    parentEvent = models.ForeignKey(ParentEvent)
    # parentEventId = models.PositiveSmallIntegerField(null=True,blank=True)

    def __str__(self):
        return 'Event:%s, EventId: %s, Category: %s' % ( self.eventName,self.eventId, self.parentEvent.categoryName, )

class Team(models.Model):
    teamName = models.CharField(max_length=250, null=True, blank=True)
    teamId = models.AutoField(primary_key = True)
    event = models.ForeignKey(Event)
    teamLeader = models.ForeignKey(KYProfile,related_name = 'teamLeader')
    members = models.ManyToManyField(KYProfile,related_name = 'members')

    def __str__(self):
        return 'Team Id: %s, Event: %s' %(self.teamId, self.event.eventName)

users/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractUser
from django.contrib.auth.base_user import AbstractBaseUser
from django.db.models.signals import post_save
from django.dispatch import receiver

from allauth.socialaccount.models import SocialToken, SocialAccount

from .manager import UserManager

year_choices = [
        (None, 'Year'),
        (1, 'First'),
        (2, 'Second'),
        (3, 'Third'),
        (4, 'Fourth'),
        (5,'Fifth'),
    ]

gender_choices = [
        (None,'Gender'),
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other')
]

class Events(models.Model):
    eventsList = models.TextField(null=True)


class College(models.Model):
    collegeName = models.CharField(max_length=250)
    regCount = models.IntegerField(default=0)

    def __str__(self):
        return '%s' % self.collegeName


class KYProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=50, unique=True)
    full_name = models.CharField(max_length=130, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=gender_choices, null=True, blank=True,default=None)
    college = models.ForeignKey(College, null=True, blank=True)
    year = models.PositiveSmallIntegerField(choices=year_choices, null=True, blank=True)
    mobile_number = models.BigIntegerField(null=True, blank=True)

    profile_link = models.CharField(max_length=300, null=True, blank=True)
    profile_picture = models.URLField(null=True, blank=True, default='https://storage.forums.net/6479407/images/vagmAzMznjBJGQf_sumV.png')
    has_ca_profile = models.BooleanField(default=False)
    profile_completed = models.BooleanField(default=False)
    ky_id = models.CharField(max_length=20, null=True, blank=True)
    referralCode = models.CharField(max_length=20, null=True, blank=True) #should be caId of some CA.
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_paid = models.BooleanField(default=False)
    payment_id = models.CharField(max_length=50,null=True,blank=True)
    paid_amt = models.IntegerField(null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    def get_short_name(self):
        return self.email

    def save(self, *args, **kwargs):
        if self.ky_id is None:
            try:
                temp = KYProfile.objects.all().order_by("-id")[0].id
                self.ky_id = 'KY%04d' % (temp + 101)
            except Exception as e:
                self.ky_id = 'KY%04d' % 101
        super(self.__class__, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" %(self.ky_id)

#instance is socialaccount, instance .user is kyprofile
def save_profile(sender, instance, **kwargs):
    instance.user.full_name = instance.extra_data['name']
    if instance.provider!='Google': #make sure the social app object's name is Google (case-sensitive)
        try:
           instance.user.gender = instance.extra_data['gender']
        except Exception as e:
            pass # sometimes google doesn't return gender :(
    instance.user.profile_link = instance.extra_data['link']
    instance.user.profile_picture = instance.get_avatar_url()
    instance.user.save()

post_save.connect(save_profile, sender=SocialAccount)


class CAProfile(models.Model):
    kyprofile = models.OneToOneField(KYProfile)

    whatsapp_number = models.BigIntegerField(null=True, blank=True)
    postal_address = models.TextField(null=True, blank=True)
    pincode = models.PositiveIntegerField(null=True, blank=True)
    reason = models.TextField(null=True, blank=True)

    regs = models.ManyToManyField(KYProfile, blank=True, related_name='regs')
    reg_num = models.PositiveIntegerField(default=0, null=True, blank=True) #no. of refered kyprofile.
    ca_id = models.CharField(max_length=20, null=True, blank=True)
    is_choosen = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.ca_id is None:
            try:
                temp = CAProfile.objects.all().order_by("-id")[0].id
                self.ca_id = 'KYCA%04d' % (temp + 101)
            except Exception as e:
                self.ca_id = 'KYCA%04d' % 101
        super(self.__class__, self).save(*args, **kwargs)


    def __str__(self):
        return "%s - %s" %(self.kyprofile.full_name, self.ca_id)

users/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext as _
from django.contrib.auth.password_validation import validate_password
from allauth.account.forms import ResetPasswordForm
from allauth.account.adapter import get_adapter
from allauth.account.utils import filter_users_by_email

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import KYProfile

class MyResetPasswordForm(ResetPasswordForm):
    def clean_email(self):
        email = self.cleaned_data["email"]
        email = get_adapter().clean_email(email)
        self.users = filter_users_by_email(email)
        if not len(self.users):
            raise forms.ValidationError(_("The e-mail address is not assigned"
                                          " to any user account"))

        elif len(self.users[0].socialaccount_set.filter(provider='facebook')):
            raise forms.ValidationError(_("You are using a social account to login you can't reset password."))
        return self.cleaned_data["email"]





class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = KYProfile
        fields = ('full_name', 'email')

event/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect,Http404, HttpResponse, render_to_response
from django.contrib.auth import authenticate, login, logout
#from KYusers.emailBackend import LoginUsingEmailAsUsernameBackend
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
import json
from django.contrib import messages
from django.contrib.messages import get_messages

from django.contrib.auth.decorators import login_required
from users.models import *
from event.models import *
from users.forms import *
from kashiyatra.settings import LOGIN_URL,LOGIN_URL_social,LOGIN_URL_email
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives

# @login_required(login_url = LOGIN_URL)
def eventPage(request):
    template_name = 'events/index.html'
    return render(request, template_name, {})

def eventCatPage(request, eventCatName):
    try:
        template_name = 'events/%s.html' % eventCatName
        get_template(template_name)
    except:
        raise Http404('Page not found')
        
    parentevent = ParentEvent.objects.get(categoryName=eventCatName.upper())
    context = {
    'events' : Event.objects.filter(parentEvent=parentevent),
    }
    print(context)
    return render(request, template_name, context)


def regCheck(request, kyprofile, event):
    print ('checking ', kyprofile)
    alreadyReg = False
    try:
        Team.objects.get(event=event, teamLeader=kyprofile)
        alreadyReg = True
    except:# not a team leader
        try:
            Team.objects.get(event=event, members=kyprofile)
            alreadyReg = True
        except:#not reg as team member too
            pass

    if alreadyReg:
        print ('alreadyReg')
        try:
            messages.info(request, '%s already registered for event : %s.' %(kyprofile.kyId, event.eventName), fail_silently=True)
        except:
            pass
    return alreadyReg


@login_required(login_url = LOGIN_URL)
def eventRegistration(request, eventName):
    event = Event.objects.get(eventName=eventName)
    template_name = 'eventRegister.html'
    context = {
        'event':event,
    }
    kyprofile = request.user
    
    regCheck(request, kyprofile, event)

    if request.method == "POST":

        post = request.POST
        print (post)
        teamName = post['teamName']
        leaderId = post['leader']
        memberIds = post.getlist("fields[]")
        try:
            teamLeader = KYProfile.objects.get(kyId = leaderId)
            regCheck(request, teamLeader, event)
        except Exception as e:
            messages.error(request, 'Team Leader\'s KY Id: %s is Invalid. (letters are case sensetive!)' %leaderId, fail_silently=True)
            return render(request, template_name, context)
        team = Team(teamName=teamName, event=event, teamLeader=teamLeader)
        membersList = []
        for Id in memberIds:
            if Id is not '':
                try:
                    kyprofile = KYProfile.objects.get(ky_id=Id)
                    regCheck(request, kyprofile, event)
                    membersList.append(kyprofile)
                except Exception as e:
                    # print e
                    messages.error(request, 'KY Id: %s is Invalid. (letters are case sensetive!)', fail_silently=True)
                    return render(request, template_name, context)

        msg = messages.get_messages(request)
        if msg:
            print (msg)
            return render(request, template_name,context)

        team.save()
        team.members.add(*membersList)
        team.save()

        messages.success(request, 'Registration for %s successfull!' %(eventName), fail_silently=True)
        return render(request, template_name, context)
    else:
        return render(request,template_name, context)





def individualReg(request):
    print("56565")
    if request.method == "POST":
        response_data = {}
        kyId = request.POST.get('ky_id')
        print(kyId)
        eventId = request.POST.get('eventId')
        print(eventId)
        try:
            kyprofile = KYProfile.objects.get(ky_id=kyId)
            print (kyprofile)
            event = Event.objects.get(eventId=eventId)
            print (event)
        except Exception as e:
            response_data['error'] = str(e)
            return HttpResponse(
                json.dumps(response_data),
                content_type = "application/json"
                )
        request=None
        print(regCheck(request,kyprofile, event))
        if not regCheck(request,kyprofile, event):
            Team.objects.create(teamLeader=kyprofile, event = event)
            response_data['status'] = 'registered'
            return HttpResponse(
                json.dumps(response_data),
                content_type = "application/json"
                )
        else:
            return HttpResponse('already registered!')
    else:
        return HttpResponse('not allowed')


def regCheckAjax(request):
    if request.method == "POST":
        response_data = {}
        kyId = request.POST.get('kyId')
        eventId = request.POST.get('eventId')
        kyprofile = KYProfile.objects.get(kyId=kyId)
        event = Event.objects.get(eventId=eventId)
        request = None
        if regCheck(request,kyprofile, event):
            response_data['status'] = 'registered'
        else:
            response_data['status'] = 'not_registered'

        return HttpResponse(
            json.dumps(response_data),
            content_type = "application/json"
            )
    else:
        return HttpResponse('not allowed')

templates/base.html
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" /> 
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta http-equiv="Cache-Control" content="no-siteapp">
  <meta http-equiv="Cache-Control" content="no-transform">
  <meta name="author" content="IIT(BHU),Varanasi">
  <meta name="format-detection" content="telephone=no, email=no, date=no, address=no">
  <meta name="description" content="Kashiyatra 2018 Cultural Festival of IIT (BHU) Varanasi India">
  <meta name="author" content="Kashiyatra">
  <meta name="title" content="Kashiyatra 2018 Cultural Festival of IIT (BHU) Varanasi India">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-106065508-1', 'auto');
  ga('send', 'pageview');

</script>

templates/ca-redirect.html
<html>
<head>
  {% include 'kybase.html' %}
	
</head>
    <link href="/static/ca-dashboard/css/bootstrap.min.css" rel="stylesheet" />
<body>

<div class="container">
<div class="row">
    <h3>Error Occured</h3>
 <ul> 
<li><p>An error occured while logging you in via facebook, please make sure your email id is linked to your Facebook account. </p></li>
<li><p>If your email id is already linked to Facebook, then make sure you have confirmed your email id on Facebook.</p></li>
<li>
<p>Refer this post for more info: <a href="https://www.facebook.com/help/376335499080938/">https://www.facebook.com/help/376335499080938/</a></p>
</li>
 </ul>   
 <p>    
 Follow Above instructions and Retry 
<a class="btn btn-info" href="https://www.facebook.com/v2.10/dialog/oauth?client_id=421719991556493&redirect_uri=http://{{ request.get_host }}/account/login&auth_type=rerequest&scope=email">Login again</a>
 </p>

 <h3>If you are still facing problem while registering on Kashiyatra Campus Ambassador Portal   <br>  Drop us an email: <a href="mailto:kashiyatra@iitbhu.ac.in">kashiyatra@iitbhu.ac.in</a></h3>
</div>
</div>
</body>
</html>

templates/email_reg.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'kybase.html' %}
  <title>Complete Profile</title>
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
  <link rel="stylesheet" href="/static/css/ca-form.css">
</head>
<style>

  input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    margin: 0; 
}

.ui-helper-hidden-accessible{
  display: none;

}
.ui-menu-item-wrapper{

  background: #f7f7f7;
  width: 30%;
}
ul {
  list-style-type: none;
}

</style>
<body>
  <div class="container">
      <div class="row">
        <hr />
          <h2>Register with Email</h2>

          <div class="row">
              <div class="col-sm-5">
                  <br>
                  <form action="" role="form" method="POST" id="ca-form" >
                    {% csrf_token %}
                      <div class="form-group float-label-control">
                          <label for="">Email</label>
                          <input type="email" class="form-control" id="email" name="email" required="true" placeholder="Email">
                      </div>

                      <div class="form-group float-label-control">
                          <label for="">Name</label>
                          <input type="text" class="form-control" id="name" name="name" required="true" placeholder="Name">
                      </div>
<div class="form-group float-label-control">
                          <label for="">Gender</label>
                          <select class="year" id="gender" name="gender" placeholder="gender" required="true" style="background-color: transparent; width:100%;;height:100%;font-size: 20px;padding: 1.5%;">
                            <option value="female">Female</option>
                            <option value="male">Male</option>
                            <option value="other">Other</option>
                            
                          </select>
                      </div>

                      <div class="form-group float-label-control">
                          <label for="">College</label>
                          <input type="text" id="id_college" name="college" class="form-control" required="true" placeholder="College">
                      </div>

                      <div class="form-group float-label-control">
                          <label for="">Choose Year</label>
                          <select class="year" id="id_year" name="year" placeholder="Year" required="true" style="background-color: transparent; width:100%;;height:100%;font-size: 20px;padding: 1.5%;">
                            <option value="1">First</option>
                            <option value="2">Second</option>
                            <option value="3">Third</option>
                            <option value="4">Fourth</option>
                            <option value="5">Fifth</option>
                          </select>
                      </div>

                      <div class="form-group float-label-control">
                          <label for="">Mobile Number</label>
                          <input type="number" class="form-control" name="mobile_number"  placeholder="Mobile Number">
                      </div>
                      <div class="form-group float-label-control">
                          <label for="">Referral Code</label>
                          <input type="text" class="form-control" name="ref"  placeholder="Referral Code">
                      </div>
                      <div class="form-group float-label-control">
                          <label for="">Password</label>
                          <input type="password" class="form-control" name="pass1" id="pass1"  placeholder="Password">
                      </div>
                         <div class="form-group float-label-control">
                          <label for="">Confirm Password</label>
                          <input type="password" class="form-control" name="pass2" id="pass2"  placeholder="Confirm Password">
                      </div>

                   

                      <button class="btn btn-submit" id="submit-button" onclick="return Validate()" type="submit">Done</button>
                  </form>


              </div>
              <div class="col-sm-4 col-sm-offset-3">
                  <div class="panel panel-default">
                      <div class="panel-heading">
                          <h3 class="panel-title">
                              Important!
                          </h3>
                      </div>
                      <div class="panel-body">
                          <ul>
                              <li>Make sure your all your information is correct.</li>

                          </ul>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

</body>
<script src="/static/js/jquery-1.11.3.min.js"></script>
<script src="/static/js/bootstrap-3.3.5.min.js"></script>
<script src="/static/js/jquery.validate-1.14.0.min.js"></script>
<script src="/static/js/jquery-validate.bootstrap-tooltip.js"></script>
<script src="/static/js/ca-form.js" charset="utf-8"></script>
<script type="text/javascript">
      var idx=window.location.toString().indexOf("#_=_");
       if (idx>0) {
         window.location = window.location.toString().substring(0, idx);
       }

       function Validate(){

        var pass1= document.getElementById("pass1").value;
        var pass2= document.getElementById("pass2").value;
        if (pass1!=pass2){
          alert("Password do no match.")
          return false;
        }
        return true;


       }



// Wait for the DOM to be ready
$(document).ready(function() {

  $("#ca-form").validate({

    rules: {

      college: "required",
      mobile_number: {
        required: true,
        minlength: 10,
        maxlength: 10,
      },
        pass1: "required",
        pass2: "required",
      pass1: {
        required: true,
        minlength: 6,
       
      },
       pass2: {
        required: true,
        minlength: 6,
       
      },
      whatsapp_number:{
        required: true,
        minlength: 10,
        maxlength: 10,
      }, 
      pincode: {
        required: true,
        minlength: 6,
        maxlength: 6,
      },
      reason:{
        required: true,
      },
    },

    submitHandler: function(form) {
      form.submit();
          $('#submit-button').prop('disabled', true);
    }
  });

});
</script>
<!-- <script src="/static/js/1.12.0jquery-ui.min.js"></script> -->

<script>

       //     $( function() {
       //   var availableTags = [
       //     {% for clg in all_colleges %}
       //         "{{clg}}",
       //     {% endfor %}
       //   ];
       //   $("#id_college").autocomplete({
       //     source: availableTags
       //   });
       // } );
       // // over write the default autocomplete function to match the option starting with term
       // $.ui.autocomplete.filter = function (array, term) {
       //   var matcher = new RegExp("^" + $.ui.autocomplete.escapeRegex(term), "i");
       //   return $.grep(array, function (value) {
       //     return matcher.test(value.label || value.value || value);
       //   });
       // };
</script>
</html>

templates/eventsRegister.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'kybase.html' %}
  <title>Complete Profile</title>
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
  <link rel="stylesheet" href="/static/css/ca-form.css">
</head>
<style>

  input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    margin: 0; 
}

.ui-helper-hidden-accessible{
  display: none;

}
.ui-menu-item-wrapper{

  background: #f7f7f7;
  width: 30%;
}
ul {
  list-style-type: none;
}

</style>
<body>
  <div class="container">
      <div class="row">
        <hr />
          <h2>Complete Your Profile</h2>

          <div class="row">
              <div class="col-sm-5">
                  <br>
                  <form action="" role="form" method="POST" id="ca-form">
                    {% csrf_token %}
                      <div class="form-group float-label-control">
                          <label for="">Events</label>
                          <input type="text" class="form-control" name="event">
                      </div>

                      <div class="form-group float-label-control">
                          <label for="">Members</label>
                          <input type="text" class="form-control" name="member" >
                      </div>
     
                      <button class="btn btn-submit"type="submit">Done</button>
                  </form>


              </div>
              <div class="col-sm-4 col-sm-offset-3">
                  <div class="panel panel-default">
                      <div class="panel-heading">
                          <h3 class="panel-title">
                              Important!
                          </h3>
                      </div>
                      <div class="panel-body">
                          <ul>
                              <li>Make sure your all your information is correct.</li>

                          </ul>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

</body>
<script src="/static/js/jquery-1.11.3.min.js"></script>
<script src="/static/js/bootstrap-3.3.5.min.js"></script>
<script src="/static/js/jquery.validate-1.14.0.min.js"></script>
<script src="/static/js/jquery-validate.bootstrap-tooltip.js"></script>
<script src="/static/js/ca-form.js" charset="utf-8"></script>
<script type="text/javascript">
      var idx=window.location.toString().indexOf("#_=_");
       if (idx>0) {
         window.location = window.location.toString().substring(0, idx);
       }



// Wait for the DOM to be ready
$(document).ready(function() {

  $("#ca-form").validate({

    rules: {

     postal_address: "required",

      whatsapp_number:{
        required: true,
        minlength: 10,
        maxlength: 10,
      }, 
      pincode: {
        required: true,
        minlength: 6,
        maxlength: 6,
      },
      reason:{
        required: true,
      },
    },

    submitHandler: function(form) {
      form.submit();
    }
  });

});
</script>
<!-- <script src="/static/js/1.12.0jquery-ui.min.js"></script> -->

<script>

       //     $( function() {
       //   var availableTags = [
       //     {% for clg in all_colleges %}
       //         "{{clg}}",
       //     {% endfor %}
       //   ];
       //   $("#id_college").autocomplete({
       //     source: availableTags
       //   });
       // } );
       // // over write the default autocomplete function to match the option starting with term
       // $.ui.autocomplete.filter = function (array, term) {
       //   var matcher = new RegExp("^" + $.ui.autocomplete.escapeRegex(term), "i");
       //   return $.grep(array, function (value) {
       //     return matcher.test(value.label || value.value || value);
       //   });
       // };
</script>
</html>

templates/schedule.html
<!DOCTYPE html>
<head>
	<title>
		Schedule | KY
	</title>
  {% include 'kybase.html' %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/static/schedule/style.css">
</head>

<body>
	<div class="bg1"><img src="/static/schedule/schedule-a3.jpg" class="image1"></div>
	<div class="bg2"><img src="/static/schedule/appwebsite.jpg" class="image2"></div>
</body>